controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

category_get:
    path: /category/{id}
    controller: App\Controller\CategoryController::getCategory
